/*
 * File: app/view/Contact.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RSS.view.Contact', {
    extend: 'Ext.form.Panel',
    alias: 'widget.contactview',

    config: {
        cls: [
            'contact-view'
        ],
        items: [
            {
                xtype: 'image',
                height: 71,
                src: 'images/logo.png'
            },
            {
                xtype: 'fieldset',
                title: 'Contact',
                items: [
                    {
                        xtype: 'textfield',
                        label: 'Email',
                        name: 'email'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                instructions: 'max char 500',
                items: [
                    {
                        xtype: 'textareafield',
                        name: 'comment'
                    }
                ]
            },
            {
                xtype: 'button',
                action: 'contact',
                height: 50,
                margin: '1em 0 0 0',
                ui: 'action',
                text: 'Contact'
            }
        ]
    }

});