/*
 * File: app/view/Login.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.Login', {
    extend: 'Ext.form.Panel',
    alias: 'widget.login',

    config: {
        id: 'login',
        ui: '',
        scrollable: false,
        items: [
            {
                xtype: 'container',
                id: 'formWrap',
                items: [
                    {
                        xtype: 'label',
                        hidden: true,
                        hideAnimation: 'fadeOut',
                        html: 'Login failed. Please enter the correct credentials.',
                        itemId: 'signInFailedLabel',
                        showAnimation: 'fadeIn',
                        style: 'color:#990000;margin:5px 0px;'
                    },
                    {
                        xtype: 'fieldset',
                        items: [
                            {
                                xtype: 'textfield',
                                itemId: 'username',
                                inputCls: 'input',
                                labelCls: 'label',
                                name: 'username',
                                required: true,
                                placeHolder: 'Username'
                            },
                            {
                                xtype: 'passwordfield',
                                itemId: 'password',
                                inputCls: 'input',
                                name: 'password',
                                required: true,
                                placeHolder: 'Password'
                            }
                        ]
                    },
                    {
                        xtype: 'button',
                        id: 'submit',
                        itemId: 'submit',
                        ui: 'confirm',
                        iconMask: true,
                        text: 'Log In'
                    }
                ]
            }
        ]
    }

});