/*
 * File: app/view/MyFormPanel7.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RSS.view.MyFormPanel7', {
    extend: 'Ext.form.Panel',
    alias: 'widget.myformpanel7',

    config: {
        cls: [
            'contact-view'
        ],
        items: [
            {
                xtype: 'image',
                height: 71,
                src: 'images/logo.png'
            },
            {
                xtype: 'fieldset',
                instructions: 'GoodSam was developed with the intent to inspire, influence, and promote acts of kindness.  ',
                title: 'About GoodSam'
            },
            {
                xtype: 'fieldset',
                instructions: 'GoodSam uses the Instagram© api to select pictures from users tagged with the hash #gooddeeds. These photos are in chronological order and can be accessed by pressing the "timeline" button on the toolbar located on the bottom of the viewport. Use of this feature does not require authentication.',
                title: 'How To Use'
            },
            {
                xtype: 'fieldset',
                instructions: 'If a user wishes to register, they may do so by navigating to the login screen, clicking the "register" button and filling out the registration form with the required information. ',
                title: 'User Registration'
            },
            {
                xtype: 'fieldset',
                instructions: 'Once registered and logged in, a user has the ability to edit their personal information as well as save their favorite "GoodDeed" RSS feeds.  A valid feed url can be added by pressing the "+" button on the top navigation bar. In order to properly view the latest news, the url MUST have a syndication feed available. Ex. http://feeds.feedburner.com/CharityNews or http://www.goodnewsnetwork.org/feed/rss/all-content.html',
                title: 'Features'
            },
            {
                xtype: 'fieldset',
                instructions: '© 2013'
            }
        ]
    }

});