/*
 * File: app/view/MyFormPanel7.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RSS.view.MyFormPanel7', {
    extend: 'Ext.form.Panel',
    alias: 'widget.myformpanel7',

    config: {
        cls: [
            'contact-view'
        ],
        items: [
            {
                xtype: 'image',
                height: 71,
                src: 'images/logo.png'
            },
            {
                xtype: 'fieldset',
                instructions: 'GoodSam was developed with the intent to inspire, influence, and promote acts of kindness.  ',
                title: 'About GoodSam'
            },
            {
                xtype: 'fieldset',
                instructions: 'GoodSam uses the Instagram© api to select pictures from users tagged with the hash #gooddeeds. These photos are in chronological order and can be accessed by pressing the "timeline" button on the toolbar located on the bottom of the viewport. Use of this feature does not require authentication.',
                title: 'How To Use'
            },
            {
                xtype: 'fieldset',
                instructions: 'If a user wishes to register, they may do so by navigating to the login screen, clicking the "register" button and filling out the registration form with the required information. ',
                title: 'User Registration'
            },
            {
                xtype: 'fieldset',
                instructions: 'Once registered and logged in, a user has the ability to edit their personal information as well as save their favorite "GoodDeed" RSS feeds.  A valid feed url can be added by pressing the "+" button on the top navigation bar. In order to properly view the latest news, the url MUST have a syndication feed available. Ex. http://feeds.feedburner.com/CharityNews or http://www.goodnewsnetwork.org/feed/rss/all-content.html',
                title: 'Features'
            },
            {
                xtype: 'fieldset',
                instructions: 'GoodSam offers this app, including all information, software, products and services available from this app or offered as part of or in conjunction with this app (the "app"), to you, the user, conditioned upon your acceptance of all of the terms, conditions, policies and notices stated here. Good Sam reserves the right to make changes to these Terms and Conditions immediately by posting the changed Terms and Conditions in this location.',
                title: 'Terms and Conditions'
            },
            {
                xtype: 'fieldset',
                instructions: 'Your continued use of the app constitutes your agreement to all such terms, conditions and notices, and any changes to the Terms and Conditions made by GoodSam.'
            },
            {
                xtype: 'fieldset',
                instructions: 'The term \'GoodSam\' or \'us\' or \'we\' refers to the owner of the app. The term \'you\' refers to the user or viewer of our app. The use of this app is subject to the following terms of use:'
            },
            {
                xtype: 'fieldset',
                instructions: 'Use the app at your own risk. This app is provided to you "as is," without warranty of any kind either express or implied. Neither GoodSam nor its employees, agents, third-party information providers, merchants, licensors or the like warrant that the app or its operation will be accurate, reliable, uninterrupted or error-free. No agent or representative has the authority to create any warranty regarding the app on behalf of GoodSam. GoodSam reserves the right to change or discontinue at any time any aspect or feature of the app.'
            },
            {
                xtype: 'fieldset',
                instructions: '© 2013'
            }
        ]
    }

});