/*
 * File: app/view/Timeline.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RSS.view.Timeline', {
    extend: 'Ext.dataview.DataView',
    alias: 'widget.timelineview',

    config: {
        id: 'timeline',
        store: 'data',
        cls: [
            'timeline-view'
        ],
        itemTpl: [
            '<div id="wrap">',
            '    ',
            '    <div class="user">',
            '  ',
            '        <img class= "avatar" src="{user.profile_picture}"/>',
            '        ',
            '        {user.username}',
            '                ',
            '    </div>',
            '',
            '    <div class="deed"><a href="{link}">',
            '        ',
            '        <img class="deedPic" src="{images.standard_resolution.url}"/></a>',
            '   ',
            '        <div class="caption">{caption.text}</div>',
            '   ',
            '    </div>',
            '    <div class="spacer">',
            '    </div>',
            '    ',
            '</div>'
        ]
    }

});