/*
 * File: app/view/Users.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RSS.view.Users', {
    extend: 'Ext.dataview.List',
    alias: 'widget.usersview',

    config: {
        store: 'Users',
        onItemDisclosure: true,
        cls: [
            'users-view'
        ],
        itemTpl: [
            '<div class="name">',
            '',
            '    <div class="profileTitle"><div class="strong">Username:</div> <div class="info">{username}</div></div>',
            '    <div class="profileTitle"><div class="strong">Name:</div><div class="info">{name}</div></div>',
            '    <div class="profileTitle"><div class="strong">Email:</div><div class="info">{email}</div></div>',
            '        ',
            '',
            '</div>'
        ]
    }

});