/*
 * File: app/view/Users.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RSS.view.Users', {
    extend: 'Ext.dataview.DataView',
    alias: 'widget.usersview',

    config: {
        id: 'view-container',
        store: 'Users',
        cls: [
            'users-view'
        ],
        itemTpl: [
            '<div class="pWrap">',
            '    <div class="pTitle">Username</div>',
            '    <div class="pinfo"><input class="x-type" type="text" value="{username}"></div>',
            '</div>',
            '',
            '<div class="pWrap">',
            '    <div class="pTitle">First</div>',
            '    <div class="pinfo"><input type="text" value="{name}"></div>',
            '</div>',
            '',
            '<div class="pWrap">',
            '    <div class="pTitle">Last</div>',
            '    <div class="pinfo"><input type="text" value="{surname}"></div>',
            '</div>',
            '',
            '<div class="pWrap">',
            '    <div class="pTitle">Email</div>',
            '    <div class="pinfo"><input type="text" value="{email}"></div>',
            '</div>',
            ''
        ]
    }

});