/*
 * File: app/view/Viewport.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RSS.view.Viewport', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.viewportview',

    requires: [
        'RSS.view.Timeline',
        'RSS.view.Main',
        'RSS.view.Contact',
        'RSS.view.MyFormPanel7'
    ],

    config: {
        activeItem: 1,
        cls: 'viewport-view',
        tabBar: {
            docked: 'bottom'
        },
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                ui: 'light',
                title: 'GoodSam'
            },
            {
                xtype: 'timelineview',
                title: 'Timeline',
                iconCls: 'time'
            },
            {
                xtype: 'mainview',
                title: 'Feeds',
                iconCls: 'bookmarks'
            },
            {
                xtype: 'contactview',
                title: 'Contact',
                iconCls: 'compose'
            },
            {
                xtype: 'myformpanel7',
                title: 'Help',
                iconCls: 'info'
            }
        ]
    }

});